# Generated by Django 3.1 on 2020-11-11 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gsportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acctID', models.CharField(max_length=5)),
                ('acctName', models.CharField(max_length=30)),
                ('providerName', models.CharField(blank=True, max_length=30)),
                ('providerURL', models.URLField(blank=True)),
                ('uploadFile', models.FileField(blank=True, upload_to='CSVfiles/')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetSymbol', models.CharField(max_length=6)),
                ('lastPrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('openingPrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('lastLook', models.DateTimeField()),
                ('assetType', models.CharField(choices=[('growth', 'growth'), ('income', 'income'), ('cash', 'cash')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('articleURL', models.URLField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='gsportal.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement', models.CharField(choices=[('UP', 'goes above'), ('DN', 'goes below')], max_length=30)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=20)),
                ('lastLook', models.DecimalField(decimal_places=2, max_digits=20)),
                ('text_notification', models.BooleanField(default=False)),
                ('email_notification', models.BooleanField(default=False)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='gsportal.asset')),
            ],
        ),
        migrations.CreateModel(
            name='AcctHolding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='gsportal.account')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='gsportal.asset')),
            ],
        ),
    ]
