# Generated by Django 3.1 on 2020-11-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsportal', '0002_account_acctholding_alert_asset_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News item', 'verbose_name_plural': 'News items'},
        ),
        migrations.AlterField(
            model_name='alert',
            name='movement',
            field=models.CharField(choices=[('goes above', 'goes above'), ('goes below', 'goes below')], max_length=30),
        ),
    ]
