# Generated by Django 3.1 on 2020-11-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsportal', '0003_auto_20201111_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='lastLook',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='lastPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='openingPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
