# Generated by Django 3.1.3 on 2020-11-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsportal', '0005_alertq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertq',
            name='alertmessage',
            field=models.CharField(max_length=50),
        ),
    ]
