# Generated by Django 3.1.4 on 2021-01-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsportal', '0007_auto_20201124_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStampNY', models.DateTimeField(blank=True, null=True)),
                ('DJIvalue', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('GSPCvalue', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('IXICvalue', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MktInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mktStatus', models.CharField(max_length=20)),
                ('lastCheckTimeNY', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
