# Generated by Django 3.1.4 on 2021-01-24 01:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gsportal', '0009_auto_20210122_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertq',
            name='alertID',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
