# Generated by Django 3.1.4 on 2021-01-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsportal', '0010_alertq_alertid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='articleURL',
            field=models.URLField(max_length=400),
        ),
        migrations.AlterField(
            model_name='news',
            name='headline',
            field=models.CharField(max_length=400),
        ),
    ]
